### ISSUE TITLE
Project appears to depend on kotlin but does not declare that as a dependency.

### ISSUE THREAD

**Issue by muksihs** [RHazDev/IPFS-Daemon#4]
```Java
import fr.rhaz.ipfs.IPFSDaemon;
import kotlin.Unit;
import kotlin.jvm.functions.Function1;

public class Ipfs {

	@BeforeTest
	public void setup(){
		IPFSDaemon ipfsd = new IPFSDaemon();
		ipfsd.download();
		Function1<? super Boolean, Unit> x;
		ipfsd.setStart(x);
	}
}

```

**Comment by muksihs** [comment]
I added the following as a gradle dependency and it seems operational:
```Gradle
compile "org.jetbrains.kotlin:kotlin-stdlib-jdk8:+"
```

**Comment by Hazae41** [comment]
Fixed in:
https://github.com/RHazDev/IPFS-Daemon/commit/97e91e32bc5e62e58f3764e23104cf8cd79d59ef

I also updated Kotlin
https://github.com/RHazDev/IPFS-Daemon/commit/bf1c51acdd338e9d35d73a84e0f3cadc738f9a17

And added Java compat functions
https://github.com/RHazDev/IPFS-Daemon/commit/7930d018ca04db2265f12cf8a8d3f5580a8ea843
